### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by SeekPoint** [bung87/bixin#3]
(venv) C:\ub16_prj\bixin>pip3 install -e ".[dev]" git+https://github.com/bung87/bixin
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/bung87/bixin
  Cloning https://github.com/bung87/bixin to c:\temp\pip-req-build-f06eh4tp
Obtaining file:///C:/ub16_prj/bixin
Collecting cppjieba-py (from bixin==0.0.2)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ae/53/ed41d2fa14a6fa38850eec69a5f97d0097fe104ae4faa7ebca8b166fee4d/cppjieba_py-0.0.10.tar.gz (5.0MB)
    100% |████████████████████████████████| 5.0MB 3.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Temp\pip-install-n7xdrboy\cppjieba-py\setup.py", line 129, in <module>
        long_description= open("README.md").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 153: illegal multibyte sequence

**Comment by bung87** [comment]
fixed by updating cppjiaba-py to 0.0.11, in any case you can try `export LC_ALL=en_US.UTF-8` to change your default encoding.
