### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by casstai** [bung87/bixin#4]
I tried to install bixin on Win10, but it always shows the error "Failed building wheel for cppjieba_py" even after reinstalling and updating wheel and trying --no-cache-dir.  I am a novice and have no idea what to do.  Thanks!

**Comment by bung87** [comment]
bixin relys on https://github.com/bung87/cppjieba-py, in order to install cppjieba-py ,you need c++ compiler support at least c++ 11, I never developing python project on windows, you may find some usefull resources from internet. first of all make sure you can compile c++ code.

**Comment by casstai** [comment]
Thanks!  I will check and install c++ first!

**Comment by casstai** [comment]
I installed C++ build tools on Windows, but still failed. The same error message "Failed to build wheel for cppjieba-py". I also tried to install Bixin in Mac, but got the same error message.  Any suggestion on installation on Mac? Thanks ahead!

**Comment by bung87** [comment]
1, check your python version , both projects are python3 
2, `gcc -v` check your gcc version ,make sure it support c++ 11
could you provide more information about this error, or screenshot?

**Comment by casstai** [comment]
On Mac, the version of gcc seems to be 4.2.1. Does it mean c++ 4.11 is needed?  The screenshots are attached. Thanks!
<img width="701" alt="Screen Shot 2019-07-17 at 11 12 38 AM" src="https://user-images.githubusercontent.com/46602397/61585979-1e334580-ab2f-11e9-8b1b-c33f9527054e.png">
<img width="706" alt="Screen Shot 2019-07-17 at 11 13 35 AM" src="https://user-images.githubusercontent.com/46602397/61585980-1e334580-ab2f-11e9-97e1-d8982f393084.png">

**Comment by bung87** [comment]
1, gcc4.2 not support c++ 11 `brew install gcc@6` then add `CC=gcc-6 CXX=g++-6` flag to your comand like `CC=gcc-6 CXX=g++-6 pip3 install ....`
2, you mess up the package install location and execute location, the screenshot show you install it to python3.7 and use it in python3.6

**Comment by casstai** [comment]
Emmm, I followed all your instruction, but it still cannot work.. There must be some problems at my side. Thanks so much for your patience and help!!
