### ISSUE TITLE
load_userdict failure

### ISSUE THREAD

**Issue by RiverGao** [bung87/bixin#6]
Hello, I installed bixin and tried to use it. However, I can't do a prediction as there's no tmpy34pb3x7.txt file in the Temp folder. How to fix this problem? Thank you.

**Comment by bung87** [comment]
hi ,there's problem with `tempfile.NamedTemporaryFile`
https://docs.python.org/3.5/library/tempfile.html#tempfile.NamedTemporaryFile
if you runs on windows there's nothing more I can do.
